dron01:
  local_pose:
    enable: True
    T: 20
  local_twist:
    enable: False
    T: 20
  data_attitude:
    enable: False
    T: 20
  data_rate: 
    enable: False
    T: 20
  data_motor: 
    enable: False
    T: 20
  data:
    enable: False
    T: 20
  task: 
    enable: True
    role: consensus
    type: distance
    relationship: 'khepera01_0.9, khepera02_0.9, dron02_0.6, dron03_0.6, dron04_0.8485'

dron02:
  local_pose:
    enable: True
    T: 20
  local_twist:
    enable: False
    T: 20
  data_attitude:
    enable: False
    T: 20
  data_rate: 
    enable: False
    T: 20
  data_motor: 
    enable: False
    T: 20
  data:
    enable: False
    T: 20
  task: 
    enable: True
    role: consensus
    type: distance
    relationship: 'dron01_0.6, dron03_0.85, dron04_0.6, khepera03_0.9, khepera02_0.9'

dron03:
  local_pose:
    enable: True
    T: 20
  local_twist:
    enable: False
    T: 20
  data_attitude:
    enable: False
    T: 20
  data_rate: 
    enable: False
    T: 20
  data_motor: 
    enable: False
    T: 20
  data:
    enable: False
    T: 20
  task: 
    enable: True
    role: consensus
    type: distance
    relationship: 'dron01_0.6, dron02_0.85, dron04_0.6, khepera01_0.9, khepera04_0.9'

dron04:
  local_pose:
    enable: True
    T: 20
  local_twist:
    enable: False
    T: 20
  data_attitude:
    enable: False
    T: 20
  data_rate: 
    enable: False
    T: 20
  data_motor: 
    enable: False
    T: 20
  data:
    enable: False
    T: 20
  task: 
    enable: True
    role: consensus
    type: distance
    relationship: 'dron01_0.8485, dron02_0.6, dron03_0.6, khepera04_0.9, khepera03_0.9'
