dron01:
  name: dron01
  control_mode: HighLevel
  controller_type: Continuous
  communication:
    type: Continuous
    threshold:
      type: Null
      co: Null
      ai: Null
  local_pose:
    enable: True
    T: 20
  local_twist:
    enable: False
    T: 20
  data_attitude:
    enable: False
    T: 20
  data_rate: 
    enable: False
    T: 20
  data_motor: 
    enable: False
    T: 20
  data:
    enable: False
    T: 20
  task: 
    enable: True
    T: 100
    Onboard: False
    role: consensus
    type: distance
    relationship: 'khepera01_0.8485, khepera02_0.8485, dron02_0.6, dron03_0.6'

dron02:
  name: dron02
  control_mode: HighLevel
  controller_type: Continuous
  communication:
    type: Continuous
    threshold:
      type: Null
      co: Null
      ai: Null
  local_pose:
    enable: True
    T: 20
  local_twist:
    enable: False
    T: 20
  data_attitude:
    enable: False
    T: 20
  data_rate: 
    enable: False
    T: 20
  data_motor: 
    enable: False
    T: 20
  data:
    enable: False
    T: 20
  task: 
    enable: True
    T: 100
    Onboard: False
    role: consensus
    type: distance
    relationship: 'khepera03_0.8485, khepera04_0.8485, dron01_0.6, dron03_0.6'

dron03:
  name: dron03
  control_mode: HighLevel
  controller_type: Continuous
  communication:
    type: Continuous
    threshold:
      type: Null
      co: Null
      ai: Null
  local_pose:
    enable: True
    T: 20
  local_twist:
    enable: False
    T: 20
  data_attitude:
    enable: False
    T: 20
  data_rate: 
    enable: False
    T: 20
  data_motor: 
    enable: False
    T: 20
  data:
    enable: False
    T: 20
  task: 
    enable: True
    T: 100
    Onboard: False
    role: consensus
    type: distance
    relationship: 'khepera02_0.8485, khepera03_0.8485, dron01_0.6, dron02_0.6'

khepera01:
  id: khepera01
  agent_ip: '192.168.0.22'
  port_number: 50000
  init_theta: 0.0
  communication:
    type: Continuous
    threshold:
      type: Null
      co: Null
      ai: Null
  task: 
    enable: True
    T: 100
    Onboard: False
    role: consensus
    type: distance
    relationship: 'khepera02_0.6, khepera03_0.8485, khepera04_0.6, dron01_0.8485'

turtlebot01:
  id: turtlebot01
  agent_ip: '192.168.0.23'
  init_theta: 0.0
  communication:
    type: Continuous
    threshold:
      type: Null
      co: Null
      ai: Null
  task: 
    enable: True
    T: 100
    Onboard: False
    role: consensus
    type: distance
    relationship: 'khepera02_0.6, khepera03_0.8485, khepera04_0.6, dron01_0.8485'

dron04:
  name: turtlebot01
  control_mode: None
  controller_type: Continuous
  communication:
    type: Continuous
    threshold:
      type: Null
      co: Null
      ai: Null
  local_pose:
    enable: True
    T: 20
  local_twist:
    enable: False
    T: 20
  data_attitude:
    enable: False
    T: 20
  data_rate: 
    enable: False
    T: 20
  data_motor: 
    enable: False
    T: 20
  data:
    enable: False
    T: 20
  task: 
    enable: False
    role: Null
    type: Null
    relationship: Null

khepera02:
  id: khepera02
  agent_ip: '192.168.0.21'
  port_number: 50000
  init_theta: -1.5707
  communication:
    type: Continuous
    threshold:
      type: Null
      co: Null
      ai: Null
  task: 
    enable: True
    T: 100
    Onboard: False
    role: consensus
    type: distance
    relationship: 'khepera01_0.6, khepera03_0.6, khepera04_0.8485, dron01_0.8485'

khepera03:
  id: khepera03
  agent_ip: '192.168.0.19'
  port_number: 50000
  init_theta: -1.5707
  communication:
    type: Continuous
    threshold:
      type: Null
      co: Null
      ai: Null
  task: 
    enable: True
    T: 100
    Onboard: False
    role: consensus
    type: distance
    relationship: 'khepera02_0.6, khepera01_0.8485, khepera04_0.6, dron02_0.8485'

khepera04:
  id: khepera04
  agent_ip: '192.168.0.20'
  port_number: 50000
  init_theta: -1.5707
  communication:
    type: Continuous
    threshold:
      type: Null
      co: Null
      ai: Null
  task: 
    enable: True
    T: 100
    Onboard: False
    role: consensus
    type: distance
    relationship: 'khepera01_0.6, khepera02_0.8485, khepera03_0.6, dron02_0.8485'

  name: khepera04
  control_mode: None
  controller_type: Continuous
  communication:
    type: Continuous
    threshold:
      type: Null
      co: Null
      ai: Null
  local_pose:
    enable: True
    T: 20
  local_twist:
    enable: False
    T: 20
  data_attitude:
    enable: False
    T: 20
  data_rate: 
    enable: False
    T: 20
  data_motor: 
    enable: False
    T: 20
  data:
    enable: False
    T: 20
  task: 
    enable: False
    role: Null
    type: Null
    relationship: Null