# Default crazyflie parameters to ros2 node
dron01:
  name: dron01
  control_mode: HighLevel
  positioning: Intern
  controller_type: PID_Continuous
  communication:
    type: EventBased
    threshold:
      type: Constant
      co: 0.01
      ai: Null
  local_pose:
    enable: True
    T: 20
  local_twist:
    enable: False
    T: 20
  data_attitude:
    enable: False
    T: 20
  data_rate: 
    enable: False
    T: 20
  data_motor: 
    enable: False
    T: 20
  data:
    enable: False
    T: 20
  task: 
    enable: True
    role: consensus
    type: distance
    relationship: 'dron02_0.7664, dron08_0.7654, dron09_1.1044, dron13_0.9444'

dron02:
  name: dron02
  control_mode: HighLevel
  positioning: Intern
  controller_type: PID_Continuous
  communication:
    type: EventBased
    threshold:
      type: Constant
      co: 0.01
      ai: Null
  local_pose:
    enable: True
    T: 20
  local_twist:
    enable: False
    T: 20
  data_attitude:
    enable: False
    T: 20
  data_rate: 
    enable: False
    T: 20
  data_motor: 
    enable: False
    T: 20
  data:
    enable: False
    T: 20
  task: 
    enable: True
    role: consensus
    type: distance
    relationship: 'dron01_0.7664, dron03_0.7654, dron09_0.8964'

dron03:
  name: dron03
  control_mode: HighLevel
  positioning: Intern
  controller_type: PID_Continuous
  communication:
    type: EventBased
    threshold:
      type: Constant
      co: 0.01
      ai: Null
  local_pose:
    enable: True
    T: 20
  local_twist:
    enable: False
    T: 20
  data_attitude:
    enable: False
    T: 20
  data_rate: 
    enable: False
    T: 20
  data_motor: 
    enable: False
    T: 20
  data:
    enable: False
    T: 20
  task: 
    enable: True
    role: consensus
    type: distance
    relationship: 'dron02_0.7654, dron04_0.7654, dron09_1.0437, dron10_0.9876'

dron04:
  name: dron04
  control_mode: HighLevel
  positioning: Intern
  controller_type: PID_Continuous
  communication:
    type: EventBased
    threshold:
      type: Constant
      co: 0.01
      ai: Null
  local_pose:
    enable: True
    T: 20
  local_twist:
    enable: False
    T: 20
  data_attitude:
    enable: False
    T: 20
  data_rate: 
    enable: False
    T: 20
  data_motor: 
    enable: False
    T: 20
  data:
    enable: False
    T: 20
  task: 
    enable: True
    role: consensus
    type: distance
    relationship: 'dron03_0.7654, dron05_0.7654, dron10_0.9131, dron11_1.1707'

dron05:
  name: dron05
  control_mode: HighLevel
  positioning: Intern
  controller_type: PID_Continuous
  communication:
    type: EventBased
    threshold:
      type: Constant
      co: 0.01
      ai: Null
  local_pose:
    enable: True
    T: 20
  local_twist:
    enable: False
    T: 20
  data_attitude:
    enable: False
    T: 20
  data_rate: 
    enable: False
    T: 20
  data_motor: 
    enable: False
    T: 20
  data:
    enable: False
    T: 20
  task: 
    enable: True
    role: consensus
    type: distance
    relationship: 'dron04_0.7654, dron06_0.7664, dron11_0.9124'

dron06:
  name: dron06
  control_mode: HighLevel
  positioning: Intern
  controller_type: PID_Continuous
  communication:
    type: EventBased
    threshold:
      type: Constant
      co: 0.01
      ai: Null
  local_pose:
    enable: True
    T: 20
  local_twist:
    enable: False
    T: 20
  data_attitude:
    enable: False
    T: 20
  data_rate: 
    enable: False
    T: 20
  data_motor: 
    enable: False
    T: 20
  data:
    enable: False
    T: 20
  task: 
    enable: True
    role: consensus
    type: distance
    relationship: 'dron05_0.7664, dron07_0.7654, dron11_0.9895, dron12_1.0415'

dron07:
  name: dron07
  control_mode: HighLevel
  positioning: Intern
  controller_type: PID_Continuous
  communication:
    type: EventBased
    threshold:
      type: Constant
      co: 0.01
      ai: Null
  local_pose:
    enable: True
    T: 20
  local_twist:
    enable: False
    T: 20
  data_attitude:
    enable: False
    T: 20
  data_rate: 
    enable: False
    T: 20
  data_motor: 
    enable: False
    T: 20
  data:
    enable: False
    T: 20
  task: 
    enable: True
    role: consensus
    type: distance
    relationship: 'dron06_0.7654, dron08_0.7632, dron12_0.8967'

dron08:
  name: dron08
  control_mode: HighLevel
  positioning: Intern
  controller_type: PID_Continuous
  communication:
    type: EventBased
    threshold:
      type: Constant
      co: 0.01
      ai: Null
  local_pose:
    enable: True
    T: 20
  local_twist:
    enable: False
    T: 20
  data_attitude:
    enable: False
    T: 20
  data_rate: 
    enable: False
    T: 20
  data_motor: 
    enable: False
    T: 20
  data:
    enable: False
    T: 20
  task: 
    enable: True
    role: consensus
    type: distance
    relationship: 'dron01_0.7654, dron07_0.7632, dron12_1.1053, dron13_0.9438'

dron09:
  name: dron09
  control_mode: HighLevel
  positioning: Intern
  controller_type: PID_Continuous
  communication:
    type: EventBased
    threshold:
      type: Constant
      co: 0.01
      ai: Null
  local_pose:
    enable: True
    T: 20
  local_twist:
    enable: False
    T: 20
  data_attitude:
    enable: False
    T: 20
  data_rate: 
    enable: False
    T: 20
  data_motor: 
    enable: False
    T: 20
  data:
    enable: False
    T: 20
  task: 
    enable: True
    role: consensus
    type: distance
    relationship: 'dron01_1.1044, dron02_0.8964, dron03_1.0437, dron10_0.7053, dron13_0.7053, dron14_0.6325'

dron10:
  name: dron10
  control_mode: HighLevel
  positioning: Intern
  controller_type: PID_Continuous
  communication:
    type: EventBased
    threshold:
      type: Constant
      co: 0.01
      ai: Null
  local_pose:
    enable: True
    T: 20
  local_twist:
    enable: False
    T: 20
  data_attitude:
    enable: False
    T: 20
  data_rate: 
    enable: False
    T: 20
  data_motor: 
    enable: False
    T: 20
  data:
    enable: False
    T: 20
  task: 
    enable: True
    role: consensus
    type: distance
    relationship: 'dron03_0.9876, dron04_0.9131, dron09_0.7053, dron11_0.7053, dron14_0.6325'

dron11:
  name: dron11
  control_mode: HighLevel
  positioning: Intern
  controller_type: PID_Continuous
  communication:
    type: EventBased
    threshold:
      type: Constant
      co: 0.01
      ai: Null
  local_pose:
    enable: True
    T: 20
  local_twist:
    enable: False
    T: 20
  data_attitude:
    enable: False
    T: 20
  data_rate: 
    enable: False
    T: 20
  data_motor: 
    enable: False
    T: 20
  data:
    enable: False
    T: 20
  task: 
    enable: True
    role: consensus
    type: distance
    relationship: 'dron04_1.1707, dron05_0.9124, dron06_0.9895, dron10_0.7053, dron12_0.7053, dron14_0.6325'

dron12:
  name: dron12
  control_mode: HighLevel
  positioning: Intern
  controller_type: PID_Continuous
  communication:
    type: EventBased
    threshold:
      type: Constant
      co: 0.01
      ai: Null
  local_pose:
    enable: True
    T: 20
  local_twist:
    enable: False
    T: 20
  data_attitude:
    enable: False
    T: 20
  data_rate: 
    enable: False
    T: 20
  data_motor: 
    enable: False
    T: 20
  data:
    enable: False
    T: 20
  task: 
    enable: True
    role: consensus
    type: distance
    relationship: 'dron06_1.0415, dron07_0.8967, dron08_1.1053, dron11_0.7053, dron13_0.7053, dron14_0.6325'

dron13:
  name: dron13
  control_mode: HighLevel
  positioning: Intern
  controller_type: PID_Continuous
  communication:
    type: EventBased
    threshold:
      type: Constant
      co: 0.01
      ai: Null
  local_pose:
    enable: True
    T: 20
  local_twist:
    enable: False
    T: 20
  data_attitude:
    enable: False
    T: 20
  data_rate: 
    enable: False
    T: 20
  data_motor: 
    enable: False
    T: 20
  data:
    enable: False
    T: 20
  task: 
    enable: True
    role: consensus
    type: distance
    relationship: 'dron01_0.9444, dron08_0.9438, dron09_0.7053, dron12_0.7053, dron14_0.6325'

dron14:
  name: dron14
  control_mode: HighLevel
  positioning: Intern
  controller_type: PID_Continuous
  communication:
    type: EventBased
    threshold:
      type: Constant
      co: 0.01
      ai: Null
  local_pose:
    enable: True
    T: 20
  local_twist:
    enable: False
    T: 20
  data_attitude:
    enable: False
    T: 20
  data_rate: 
    enable: False
    T: 20
  data_motor: 
    enable: False
    T: 20
  data:
    enable: False
    T: 20
  task: 
    enable: True
    role: consensus
    type: distance
    relationship: 'dron09_0.6325, dron10_0.6325, dron11_0.6325, dron12_0.6325, dron13_0.6325'
